# Generated by Django 2.2.2 on 2019-07-23 02:13

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_auto_20190722_0021'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='rating',
        ),
        migrations.AddField(
            model_name='song',
            name='rating',
            field=models.IntegerField(default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
        migrations.DeleteModel(
            name='Rating',
        ),
    ]
