# Generated by Django 2.2.2 on 2019-09-05 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0012_auto_20190905_1910'),
    ]

    operations = [
        migrations.AddField(
            model_name='usersong',
            name='completed',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
