# Generated by Django 2.2.2 on 2019-09-05 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0013_usersong_completed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersong',
            name='completed',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
