# Generated by Django 2.2.2 on 2019-09-06 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0014_auto_20190905_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersong',
            name='completed',
            field=models.CharField(default='N', max_length=1),
        ),
    ]
