# Generated by Django 2.2.2 on 2019-08-18 21:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0010_auto_20190813_0044'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrating',
            name='priority',
            field=models.IntegerField(blank=True, default=0, validators=[django.core.validators.MaxValueValidator(100), django.core.validators.MinValueValidator(0)]),
        ),
    ]
