# Generated by Django 2.2.2 on 2019-10-10 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='tag_values',
        ),
        migrations.RemoveField(
            model_name='itemtagvalue',
            name='inventory',
        ),
        migrations.AddField(
            model_name='list',
            name='tag_values',
            field=models.ManyToManyField(related_name='lists', related_query_name='list', to='lists.ItemTagValue'),
        ),
    ]
