# Generated by Django 2.2.2 on 2019-10-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lists', '0002_auto_20191010_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='itemtagvalue',
            name='value',
            field=models.CharField(blank=True, default='-', max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
